title: Zhengyuan Wang's Homepage
page-top-title: Zhengyuan Wang
top-section-bg-text: Computer Science
home-subtitle: Zhengyuan Wang&ensp;|&ensp;王正远
copyright-text: '&copy; Zhengyuan Wang 2023-2024. All Rights Reserved.'
